<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Estimating design-comparable standardized mean differences with scdhlm • scdhlm</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/cosmo/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><!-- docsearch --><script src="../docsearch.js"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.3/docsearch.min.css" integrity="sha256-QOSRU/ra9ActyXkIBbiIB144aDBdtvXBcNc3OTNuX/Q=" crossorigin="anonymous">
<link href="../docsearch.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script><meta property="og:title" content="Estimating design-comparable standardized mean differences with scdhlm">
<meta property="og:description" content="scdhlm">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    

    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">scdhlm</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="">0.5.2.999</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Estimating-effect-sizes.html">Estimating design-comparable standardized mean differences with scdhlm</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/jepusto/scdhlm/" class="external-link">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
<form class="navbar-form navbar-right hidden-xs hidden-sm" role="search">
        <div class="form-group">
          <input type="search" class="form-control" name="search-input" id="search-input" placeholder="Search..." aria-label="Search for..." autocomplete="off">
</div>
      </form>
      
    </div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="Estimating-effect-sizes_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Estimating design-comparable standardized mean differences with scdhlm</h1>
                        <h4 data-toc-skip class="author">James E. Pustejovsky</h4>
            
            <h4 data-toc-skip class="date">2021-10-05</h4>
      
      
      <div class="hidden name"><code>Estimating-effect-sizes.Rmd</code></div>

    </div>

    
    
<p>The scdhlm package (Pustejovsky, Chen, &amp; Hamilton, 2020) provides several methods for estimating design-comparable standardized mean differences (SMDs) based on data from a single-case design. In principle, a design-comparable SMD is in the same metric as the SMD from a simple, between-groups randomized experiment performed on a comparable sample and with comparable outcome measures. Hedges, Pustejovsky, and Shadish (2012) proposed methods for estimating design-comparable SMDs based on data from an ABAB design (and, more generally, treatment reversal designs with an arbitrary number of phases). Hedges, Pustejovsky, and Shadish (2013) extended the methods to handle data from multiple baseline designs. In both cases, the proposed estimation methods are premised on a simple model for the data, which assumed that the outcome process is stable over time (lacking time trends) and that the treatment effect is constant across cases. Pustejovsky, Hedges, and Shadish (2014) proposed an approach to defining and estimating design-comparable SMDs under a more general model, which can allow for time trends and between-case variation in treatment effects and time trends.</p>
<p>In the scdhlm package, the original estimation methods proposed for the ABAB design and multiple baseline design are implemented in the <code>effect_size_ABk</code> and <code>effect_size_MB</code> functions, respectively. Both of these functions take the raw data as input and produce as output an effect size estimate, along with accompanying standard error and some other auxiliary information. Thus, there is no distinction between estimating the model and estimating the effect size. In contrast, the more general methods proposed in Pustejovsky, Hedges, and Shadish (2014) entail two steps: first, estimating a hierarchical model for the data; and second, estimating a design-comparable effect size based on the fitted model. The first step is accomplished using the function <code>lme</code> from the package <code>nlme</code> by Pinheiro, Bates, DebRoy, and Sarkar (2015). The second step is accomplished using the function <code>g_mlm</code> from the <code>scdhlm</code> package. This vignette demonstrates how to use all of these functions to estimate design-comparable standardized mean difference effect sizes. The R code presented below can be used to replicate the examples found in the papers that proposed the methods. To begin, the user must load the package:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://jepusto.github.io/scdhlm/">scdhlm</a></span><span class="op">)</span></code></pre></div>
<div id="lambert-cartledge-heward-lo-2006" class="section level2">
<h2 class="hasAnchor">
<a href="#lambert-cartledge-heward-lo-2006" class="anchor" aria-hidden="true"></a>Lambert, Cartledge, Heward, &amp; Lo (2006)</h2>
<p>Lambert, Cartledge, Heward, and Lo (2006) tested the effect of using response cards (compared to single-student responding) during math lessons in two fourth-grade classrooms. The investigators collected data on rates of disruptive behavior for nine focal students, using an ABAB design. This example is discussed in Hedges, Pustejovsky, and Shadish (2012), who selected it because the design was close to balanced and used a relatively large number of cases. Their calculations can be replicated using the <code>effect_size_ABk</code> function. To use this function, the user must provide five pieces of data:</p>
<ul>
<li>the outcome variable,</li>
<li>a variable indicating the treatment condition,</li>
<li>a variable listing the case on which the outcome was measured,</li>
<li>a variable indicating the phase of treatment (i.e., each replication of a baseline and treatment condition), and</li>
<li>a variable listing the session number.</li>
</ul>
<p>In the <code>Lambert</code> dataset, these variables are called respectively <code>outcome</code>, <code>treatment</code>, <code>case</code>, <code>phase</code>, and <code>time</code>. Given these inputs, the design-comparable SMD is calculated as follows:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Lambert</span><span class="op">)</span>

<span class="va">Lambert_ES</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_ABk.html">effect_size_ABk</a></span><span class="op">(</span>outcome <span class="op">=</span> <span class="va">outcome</span>, treatment <span class="op">=</span> <span class="va">treatment</span>, 
                              id <span class="op">=</span> <span class="va">case</span>, phase <span class="op">=</span> <span class="va">phase</span>, time <span class="op">=</span> <span class="va">time</span>, 
                              data <span class="op">=</span> <span class="va">Lambert</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">Lambert_ES</span>, <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>##                              est      se
## unadjusted effect size  -2.52460 0.20228
## adjusted effect size    -2.51307 0.20136
## degree of freedom      164.49227</code></pre>
<p>The adjusted effect size estimate <code>delta_hat</code> is equal to -2.513; its variance <code>V_delta_hat</code> is equal to 0.041. A standard error for <code>delta_hat</code> can be calculated by taking the square root of <code>V_delta_hat</code>: <code>sqrt(Lambert_ES$V_delta_hat)</code> = 0.201. The effect size estimate is bias-corrected in a manner analogous to Hedges’ g correction for SMDs from a between-subjects design. The degrees of freedom <code>nu</code> are estimated based on a Satterthwaite-type approximation, which is equal to 164.5 in this example.</p>
<p>A summary() method is included to return more detail about the model parameter estimates and effect size estimates:</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">Lambert_ES</span><span class="op">)</span></code></pre></div>
<pre><code>##                                       est    se
## within-case variance                4.534      
## sample variance                     4.674      
## intra-class correlation             0.030      
## auto-correlation                    0.225      
## numerator of effect size estimate  -5.458      
## unadjusted effect size             -2.525 0.202
## adjusted effect size               -2.513 0.201
## degree of freedom                 164.492      
## scalar constant                     0.145</code></pre>
<p>By default, the <code>effect_size_ABk</code> function calculates an estimate of the first-order autocorrelation in the outcome series (stored in the entry <code>phi</code>) and an estimate of the intra-class correlation, i.e., the ratio of the between-case variance in the outcome to the total cross-sectional variance in the outcome (the intra-class correlation estimate is stored in the entry <code>rho</code>). Optionally, the user can specify their own estimates of these parameters as inputs to the function. In this example, the auto-correlation estimate was 0.225. The following code examines the sensitivity of the results to values of the auto-correlation that are larger and smaller than the default estimate of 0.225.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Lambert_ES2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_ABk.html">effect_size_ABk</a></span><span class="op">(</span>outcome <span class="op">=</span> <span class="va">outcome</span>, treatment <span class="op">=</span> <span class="va">treatment</span>, 
                id <span class="op">=</span> <span class="va">case</span>, phase <span class="op">=</span> <span class="va">phase</span>, time <span class="op">=</span> <span class="va">time</span>, 
                data <span class="op">=</span> <span class="va">Lambert</span>, phi <span class="op">=</span> <span class="fl">0.10</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">Lambert_ES2</span>, digits <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>##                              est      se
## unadjusted effect size  -2.52460 0.19376
## adjusted effect size    -2.51265 0.19285
## degree of freedom      158.73064</code></pre>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Lambert_ES3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_ABk.html">effect_size_ABk</a></span><span class="op">(</span>outcome <span class="op">=</span> <span class="va">outcome</span>, treatment <span class="op">=</span> <span class="va">treatment</span>, 
                id <span class="op">=</span> <span class="va">case</span>, phase <span class="op">=</span> <span class="va">phase</span>, time <span class="op">=</span> <span class="va">time</span>, 
                data <span class="op">=</span> <span class="va">Lambert</span>, phi <span class="op">=</span> <span class="fl">0.35</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/print.html" class="external-link">print</a></span><span class="op">(</span><span class="va">Lambert_ES3</span>, digits <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>##                              est      se
## unadjusted effect size  -2.52460 0.21697
## adjusted effect size    -2.51217 0.21591
## degree of freedom      152.57482</code></pre>
<p>The estimated auto-correlation has only a trivial effect on the effect size estimate and a minor effect on its estimated variance.</p>
</div>
<div id="anglesea-hoch-taylor-2008" class="section level2">
<h2 class="hasAnchor">
<a href="#anglesea-hoch-taylor-2008" class="anchor" aria-hidden="true"></a>Anglesea, Hoch, &amp; Taylor (2008)</h2>
<p>Anglesea, Hoch, and Taylor (2008) used an ABAB design to test the effect of using a pager prompt to reduce the rapid eating of three teenage boys with autism. The primary outcome was a measure of how quickly each participant consumed one serving of a familiar food. This example is discussed in Hedges, Pustejovsky, and Shadish (2012), who used it to illustrate the calculation of the design-comparable SMD when based on the minimum required number of cases. Their calculations can be replicated using the following code:</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Anglesea</span><span class="op">)</span>
<span class="va">Anglesea_ES</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_ABk.html">effect_size_ABk</a></span><span class="op">(</span><span class="va">outcome</span>, <span class="va">condition</span>, <span class="va">case</span>, <span class="va">phase</span>, <span class="va">session</span>, data <span class="op">=</span> <span class="va">Anglesea</span><span class="op">)</span>
<span class="va">Anglesea_ES</span></code></pre></div>
<pre><code>##                          est    se
## unadjusted effect size 1.793 2.436
## adjusted effect size   1.150 1.562
## degree of freedom      2.340</code></pre>
<p>Note that the standard error of the effect size estimate is quite large and the degrees of freedom corresponding to the denominator of the SMD estimate are very low. Both quantities are extreme due to the small number of cases used in this example.</p>
</div>
<div id="saddler-behforooz-asaro-2008" class="section level2">
<h2 class="hasAnchor">
<a href="#saddler-behforooz-asaro-2008" class="anchor" aria-hidden="true"></a>Saddler, Behforooz, &amp; Asaro (2008)</h2>
<p>Saddler, Behforooz, and Asaro (2008) used a multiple baseline design to investigate the effect of an instructional technique on the writing of fourth grade students. The investigators assessed the intervention’s effect on measures of writing quality, sentence complexity, and use of target constructions.</p>
<p>Design-comparable SMDs can be estimated based on these data using the <code>effect_size_MB</code> function. The syntax for this function is similar to that of the <code>effect_size_ABk</code> function, but does not require the user to input information about the phase of the design (because in the multiple baseline design, phase exactly corresponds to treatment condition). The following code replicates the calculations reported in Hedges, Pustejovsky, and Shadish (2013):</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Saddler</span><span class="op">)</span>

<span class="va">quality_ES</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_MB.html">effect_size_MB</a></span><span class="op">(</span><span class="va">outcome</span>, <span class="va">treatment</span>, <span class="va">case</span>, <span class="va">time</span>, 
                             data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Saddler</span>, <span class="va">measure</span><span class="op">==</span><span class="st">"writing quality"</span><span class="op">)</span><span class="op">)</span>
<span class="va">complexity_ES</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_MB.html">effect_size_MB</a></span><span class="op">(</span><span class="va">outcome</span>, <span class="va">treatment</span>, <span class="va">case</span>, <span class="va">time</span> , 
                                data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Saddler</span>, <span class="va">measure</span><span class="op">==</span><span class="st">"T-unit length"</span><span class="op">)</span><span class="op">)</span>
<span class="va">construction_ES</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_MB.html">effect_size_MB</a></span><span class="op">(</span><span class="va">outcome</span>, <span class="va">treatment</span>, <span class="va">case</span>, <span class="va">time</span>, 
                                  data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Saddler</span>, <span class="va">measure</span><span class="op">==</span><span class="st">"number of constructions"</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>
  quality <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">quality_ES</span><span class="op">)</span>,
  complexity <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">complexity_ES</span><span class="op">)</span>, 
  construction <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">construction_ES</span><span class="op">)</span> 
<span class="op">)</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"delta_hat"</span>,<span class="st">"V_delta_hat"</span>,<span class="st">"nu"</span>,<span class="st">"phi"</span>,<span class="st">"rho"</span><span class="op">)</span>,<span class="op">]</span></code></pre></div>
<pre><code>##                quality  complexity construction
## delta_hat   1.96307272  0.78540043   0.74755356
## V_delta_hat 0.33491289  0.08023320   0.07847359
## nu          8.91814603  9.60204004   7.57981360
## phi         0.09965017 -0.07542229  -0.11159420
## rho         0.63321198  0.61453091   0.73123744</code></pre>
<p>For multiple baseline designs, an alternative to using the <code>effect_size_MB</code> function is to estimate a hierarchical linear model for the data and then use the <code>g_mlm</code> function. The two alternative approaches differ in how the model parameters and effect size are estimated. Pustejovsky, Hedges, and Shadish (2014) found that the latter approach (based on a hierarchical linear model) has comparable mean-squared error to the former approach, while producing better estimates of the variance of the effect size. The latter approach is implemented in two steps, which we will demonstrate using the writing quality measure. First, we estimate the hierarchical model with an AR(1) within-case error structure using the <code>lme</code> function:</p>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">quality_RML</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html" class="external-link">lme</a></span><span class="op">(</span>fixed <span class="op">=</span> <span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span>, 
                   random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">case</span>, 
                   correlation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/corAR1.html" class="external-link">corAR1</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">~</span> <span class="va">time</span> <span class="op">|</span> <span class="va">case</span><span class="op">)</span>, 
                   data <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/subset.html" class="external-link">subset</a></span><span class="op">(</span><span class="va">Saddler</span>, <span class="va">measure</span><span class="op">==</span><span class="st">"writing quality"</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">quality_RML</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: subset(Saddler, measure == "writing quality") 
##        AIC      BIC    logLik
##   97.31383 105.6316 -43.65692
## 
## Random effects:
##  Formula: ~1 | case
##         (Intercept)  Residual
## StdDev:   0.6621631 0.6656806
## 
## Correlation Structure: ARMA(1,0)
##  Formula: ~time | case 
##  Parameter estimate(s):
##      Phi1 
## 0.3819756 
## Fixed effects:  outcome ~ treatment 
##                       Value Std.Error DF  t-value p-value
## (Intercept)        2.437206 0.3187517 34 7.646094       0
## treatmenttreatment 2.181029 0.2340101 34 9.320237       0
##  Correlation: 
##                    (Intr)
## treatmenttreatment -0.308
## 
## Standardized Within-Group Residuals:
##        Min         Q1        Med         Q3        Max 
## -1.4700055 -0.4627404 -0.1907942  0.4286209  1.8063844 
## 
## Number of Observations: 41
## Number of Groups: 6</code></pre>
<p>The summary of the fitted model displays estimates of the component parameters, including the within-case and between-case standard deviations, auto-correlation, and (unstandardized) treatment effect estimate. The next step is to combine these estimated components into an effect size estimate using the <code>g_mlm</code> function. This function takes the fitted <code>lme</code> model object as input, followed by the vectors <code>p_const</code> and <code>r_const</code>, which specify the components of the fixed effects and variance estimates that are to be used in constructing the design-comparable SMD. For details on how to choose these constants, see Pustejovsky, Hedges, and Shadish (2014). In this example:</p>
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">quality_ES_RML</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">quality_RML</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, 
                         r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, returnModel <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">quality_ES_RML</span><span class="op">)</span></code></pre></div>
<pre><code>##                                          est    se
## Tau.case.case.var((Intercept))         0.438 0.357
## cor_params                             0.382 0.230
## sigma_sq                               0.443 0.154
## total variance                         0.882 0.360
## (Intercept)                            2.437 0.319
## treatmenttreatment                     2.181 0.234
## treatment effect at a specified time   2.181 0.234
## unadjusted effect size                 2.323 0.595
## adjusted effect size                   2.174 0.557
## degree of freedom                     11.963      
## constant kappa                         0.249      
## logLik                               -43.657</code></pre>
<p>The adjusted SMD effect size is estimated as <code>g_AB</code> = 2.174; its standard error is <code>SE_g_AB</code> = 0.557; the estimated auto-correlation is <code>phi</code> = 0.382; and the estimated degrees of freedom is <code>nu</code> = 12. In this example, the RML effect size estimate is about 10% larger than the estimate from <code>effect_size_MB</code>, with a slightly smaller variance estimate. The RML estimate of the auto-correlation is substantially higher than before, but <code>effect_size_MB</code> uses a moment estimator that is known to be biased towards zero and that does not perform well when outcomes are intermittently missing for some sessions (as is the case here).</p>
</div>
<div id="laski-charlop-schreibman-1988" class="section level2">
<h2 class="hasAnchor">
<a href="#laski-charlop-schreibman-1988" class="anchor" aria-hidden="true"></a>Laski, Charlop, &amp; Schreibman (1988)</h2>
<p>Laski, Charlop, and Schreibman (1988) used a multiple baseline across individuals to evaluate the effect of a training program for parents on the speech production of their autistic children, as measured using a partial interval recording procedure. The design included eight children; one child was measured separately with each parent; for purposes of simplicity, and following Hedges, Pustejovsky, and Shadish (2013), only the measurements taken with the mother are included in the analysis.</p>
<p>The following code compares the estimates of the design-comparable SMD effect size based on the Hedges, Pustejovsky, and Shadish (2013) approach (using the <code>effect_size_MB</code> function) to the estimates based on the hierarchical linear modeling approach described in Pustejovsky, Hedges, and Shadish (2014) (using the <code>g_mlm</code> function).</p>
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Laski</span><span class="op">)</span>

<span class="co"># Hedges, Pustejovsky, &amp; Shadish (2013)</span>
<span class="va">Laski_ES_HPS</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/effect_size_MB.html">effect_size_MB</a></span><span class="op">(</span><span class="va">outcome</span>, <span class="va">treatment</span>, <span class="va">case</span>, <span class="va">time</span>, data<span class="op">=</span> <span class="va">Laski</span><span class="op">)</span>

<span class="co"># Pustejovsky, Hedges, &amp; Shadish (2014)</span>
<span class="va">Laski_RML</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html" class="external-link">lme</a></span><span class="op">(</span>fixed <span class="op">=</span> <span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span>,
                 random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">case</span>, 
                 correlation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/corAR1.html" class="external-link">corAR1</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">~</span> <span class="va">time</span> <span class="op">|</span> <span class="va">case</span><span class="op">)</span>, 
                 data <span class="op">=</span> <span class="va">Laski</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">Laski_RML</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Laski 
##        AIC      BIC    logLik
##   1048.285 1062.466 -519.1424
## 
## Random effects:
##  Formula: ~1 | case
##         (Intercept) Residual
## StdDev:    15.68278  13.8842
## 
## Correlation Structure: AR(1)
##  Formula: ~time | case 
##  Parameter estimate(s):
##      Phi 
## 0.252769 
## Fixed effects:  outcome ~ treatment 
##                       Value Std.Error  DF   t-value p-value
## (Intercept)        39.07612  5.989138 119  6.524498       0
## treatmenttreatment 30.68366  2.995972 119 10.241637       0
##  Correlation: 
##                    (Intr)
## treatmenttreatment -0.272
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.72642154 -0.69387388  0.01454473  0.69861200  2.14528141 
## 
## Number of Observations: 128
## Number of Groups: 8</code></pre>
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Laski_ES_RML</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">Laski_RML</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>

<span class="co"># compare the estimates</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>
  HPS <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">Laski_ES_HPS</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span>SMD <span class="op">=</span> <span class="va">delta_hat</span>, SE <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html" class="external-link">sqrt</a></span><span class="op">(</span><span class="va">V_delta_hat</span><span class="op">)</span>, 
                             phi <span class="op">=</span> <span class="va">phi</span>, rho <span class="op">=</span> <span class="va">rho</span>, nu <span class="op">=</span> <span class="va">nu</span><span class="op">)</span><span class="op">)</span>,
  RML <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/with.html" class="external-link">with</a></span><span class="op">(</span><span class="va">Laski_ES_RML</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="va">g_AB</span>, <span class="va">SE_g_AB</span>, <span class="va">theta</span><span class="op">$</span><span class="va">cor_params</span>, 
                             <span class="va">theta</span><span class="op">$</span><span class="va">Tau</span><span class="op">$</span><span class="va">case</span> <span class="op">/</span> <span class="op">(</span><span class="va">theta</span><span class="op">$</span><span class="va">Tau</span><span class="op">$</span><span class="va">case</span> <span class="op">+</span> <span class="va">theta</span><span class="op">$</span><span class="va">sigma_sq</span><span class="op">)</span>, <span class="va">nu</span><span class="op">)</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<pre><code>##             HPS        RML
## SMD  1.38838504  1.4048872
## SE   0.31701943  0.2863249
## phi  0.01652579  0.2527690
## rho  0.69396648  0.5606064
## nu  13.10041496 18.5524061</code></pre>
<p>As in the Saddler example, both methods produce very similar SMD estimates and variance estimates. The RML estimate of auto-correlation is substantially higher than the HPS estimate, while the intra-class correlation estimate is somewhat lower; in combination, these differences lead to larger degrees of freedom.</p>
<p>An advantage of the RML approach is that it is readily extended to more complex models. The above analysis was based on the assumption that the treatment effect is constant across cases. This assumption can be removed by fitting a model that includes a random treatment effect for each case:</p>
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Laski_RML2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html" class="external-link">lme</a></span><span class="op">(</span>fixed <span class="op">=</span> <span class="va">outcome</span> <span class="op">~</span> <span class="va">treatment</span>,
                 random <span class="op">=</span> <span class="op">~</span> <span class="va">treatment</span> <span class="op">|</span> <span class="va">case</span>, 
                 correlation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/corAR1.html" class="external-link">corAR1</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">~</span> <span class="va">time</span> <span class="op">|</span> <span class="va">case</span><span class="op">)</span>, 
                 data <span class="op">=</span> <span class="va">Laski</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">Laski_RML2</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Laski 
##        AIC      BIC    logLik
##   1036.014 1055.868 -511.0069
## 
## Random effects:
##  Formula: ~treatment | case
##  Structure: General positive-definite, Log-Cholesky parametrization
##                    StdDev   Corr  
## (Intercept)        21.79581 (Intr)
## treatmenttreatment 13.24108 -0.869
## Residual           11.94109       
## 
## Correlation Structure: AR(1)
##  Formula: ~time | case 
##  Parameter estimate(s):
##        Phi 
## 0.02267299 
## Fixed effects:  outcome ~ treatment 
##                       Value Std.Error  DF  t-value p-value
## (Intercept)        38.45243  7.881197 119 4.879008       0
## treatmenttreatment 31.59161  5.178366 119 6.100691       0
##  Correlation: 
##                    (Intr)
## treatmenttreatment -0.835
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -3.12357773 -0.50574784 -0.01605527  0.65004147  2.05388331 
## 
## Number of Observations: 128
## Number of Groups: 8</code></pre>
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html" class="external-link">anova</a></span><span class="op">(</span><span class="va">Laski_RML</span>, <span class="va">Laski_RML2</span><span class="op">)</span></code></pre></div>
<pre><code>##            Model df      AIC      BIC    logLik   Test  L.Ratio p-value
## Laski_RML      1  5 1048.285 1062.466 -519.1424                        
## Laski_RML2     2  7 1036.014 1055.868 -511.0069 1 vs 2 16.27091   3e-04</code></pre>
<p>The fit of the two models can be compared using a likelihood ratio test, which rejects the model with a constant treatment effect. The second model, which allows the treatment effect to vary, is to be preferred. The following code estimates a design-comparable SMD based on the better-fitting model.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Laski_ES_RML2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">Laski_RML2</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span>, r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">Laski_ES_RML2</span></code></pre></div>
<pre><code>##                           est    se
## unadjusted effect size  1.271 0.386
## adjusted effect size    1.181 0.358
## degree of freedom      10.776</code></pre>
<p>The adjusted effect size estimate that is 16% smaller than the estimate from the simpler model; with a standard error that is 25% larger. The difference between the two models is due to a difference in between-case variance across phases not captured by the assumptions of the simpler model. The between-case variation in the outcome appears to be substantially larger in the baseline phase than in the treatment phase. Maintaining the constant treatment effect assumption constrains the between-case variance to be constant across phases, and so the between-case variance is estimated by pooling across both phases. The constant treatment effect assumption therefore leads to a smaller variance estimate than the estimate based on allowing the between-case variance to differ by phase.</p>
</div>
<div id="schutte-malouff-brown-2008" class="section level2">
<h2 class="hasAnchor">
<a href="#schutte-malouff-brown-2008" class="anchor" aria-hidden="true"></a>Schutte, Malouff, &amp; Brown (2008)</h2>
<p>Schutte, Malouff, and Brown (2008) evaluated the effect of an emotion-focused therapy program for adults with prolonged fatigue using a multiple baseline across individuals. The design included 13 adults who met clinical criteria for prolonged fatigue. Fatigue severity was measured weekly using a self-reported scale that ranged from 1 to 63. Following Pustejovsky, Hedges, and Shadish (2014), the data for participant 4 are excluded from the analysis because nearly all of the measurements for this case are at the upper extreme of the scale. The data for the remaining participants are plotted below.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html" class="external-link">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org" class="external-link">ggplot2</a></span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/data.html" class="external-link">data</a></span><span class="op">(</span><span class="va">Schutte</span><span class="op">)</span>

<span class="fu"><a href="../reference/graph_SCD.html">graph_SCD</a></span><span class="op">(</span>case <span class="op">=</span> <span class="va">case</span>, phase <span class="op">=</span> <span class="va">treatment</span>,
          session <span class="op">=</span> <span class="va">week</span>, outcome <span class="op">=</span> <span class="va">fatigue</span>,
          design <span class="op">=</span> <span class="st">"MB"</span>, data <span class="op">=</span> <span class="va">Schutte</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html" class="external-link">facet_wrap</a></span><span class="op">(</span><span class="op">~</span> <span class="va">case</span>, ncol <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html" class="external-link">theme</a></span><span class="op">(</span>legend.position <span class="op">=</span> <span class="st">"bottom"</span><span class="op">)</span></code></pre></div>
<p><img src="Estimating-effect-sizes_files/figure-html/Schutte-graph-1.png" width="672"></p>
<p>Time trends are apparent in the outcome series, as are changes in slope in the treatment condition. In order to operationally define a design-comparable SMD effect sizes in a model that includes time trends and treatment-by-time interactions, one will need to choose a time point A at which the treatment would begin and a time point B at which outcomes would be measured, both in a hypothetical between-subjects design based on the same population of participants. Here, we take A = 2 and B = 9; centering time at week 9 simplifies the effect size calculations.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># time-point constants</span>
<span class="va">A</span> <span class="op">&lt;-</span> <span class="fl">2</span>
<span class="va">B</span> <span class="op">&lt;-</span> <span class="fl">9</span>
<span class="co"># center at follow-up time</span>

<span class="co"># create time-by-trt interaction</span>
<span class="va">Schutte</span> <span class="op">&lt;-</span> 
  <span class="fu"><a href="../reference/preprocess_SCD.html">preprocess_SCD</a></span><span class="op">(</span>case <span class="op">=</span> <span class="va">case</span>, phase <span class="op">=</span> <span class="va">treatment</span>,
                 session <span class="op">=</span> <span class="va">week</span>, outcome <span class="op">=</span> <span class="va">fatigue</span>,
                 design <span class="op">=</span> <span class="st">"MB"</span>, center <span class="op">=</span> <span class="va">B</span>, data <span class="op">=</span> <span class="va">Schutte</span><span class="op">)</span></code></pre></div>
<p>Having completed the data-cleaning process, three different models will be considered, again following the example from Pustejovsky, Hedges, and Shadish (2014).</p>
<div id="varying-intercepts-fixed-treatment-effect-fixed-trends" class="section level3">
<h3 class="hasAnchor">
<a href="#varying-intercepts-fixed-treatment-effect-fixed-trends" class="anchor" aria-hidden="true"></a>Varying intercepts, fixed treatment effect, fixed trends</h3>
<p>The initial model allows for a baseline time trend, treatment effect, and treatment-by-time interaction, all of which are assumed to be constant across the 12 cases; only the baseline intercept is assumed to vary across cases. This specification corresponds to Model MB3 from Pustejovsky, Hedges, and Shadish (2014)</p>
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lme.html" class="external-link">lme</a></span><span class="op">(</span>fixed <span class="op">=</span> <span class="va">fatigue</span> <span class="op">~</span> <span class="va">week</span> <span class="op">+</span> <span class="va">treatment</span> <span class="op">+</span> <span class="va">week_trt</span>, 
            random <span class="op">=</span> <span class="op">~</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">case</span>, 
            correlation <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/nlme/man/corAR1.html" class="external-link">corAR1</a></span><span class="op">(</span><span class="fl">0</span>, <span class="op">~</span> <span class="va">week</span> <span class="op">|</span> <span class="va">case</span><span class="op">)</span>,
            data <span class="op">=</span> <span class="va">Schutte</span>,
            method <span class="op">=</span> <span class="st">"REML"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">hlm1</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Schutte 
##        AIC     BIC    logLik
##   884.1744 904.354 -435.0872
## 
## Random effects:
##  Formula: ~1 | case
##         (Intercept) Residual
## StdDev:    3.842612 9.950088
## 
## Correlation Structure: AR(1)
##  Formula: ~week | case 
##  Parameter estimate(s):
##       Phi 
## 0.8092339 
## Fixed effects:  fatigue ~ week + treatment + week_trt 
##                       Value Std.Error  DF   t-value p-value
## (Intercept)        52.93290  4.422164 121 11.969907  0.0000
## week                0.48856  0.622153 121  0.785274  0.4338
## treatmenttreatment -1.37267  1.971510 121 -0.696253  0.4876
## week_trt           -1.89613  0.938154 121 -2.021131  0.0455
##  Correlation: 
##                    (Intr) week   trtmnt
## week                0.805              
## treatmenttreatment -0.119 -0.069       
## week_trt           -0.761 -0.777 -0.263
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.69578897 -0.64000820 -0.06285371  0.65265931  2.01491696 
## 
## Number of Observations: 136
## Number of Groups: 12</code></pre>
<p>The design-comparable standardized mean difference corresponds to the treatment effect at week <span class="math inline">\(B = 9\)</span>, after <span class="math inline">\(B - A = 7\)</span> weeks of treatment. The corresponding values of <code>p_const</code> and <code>r_const</code> are specified below.</p>
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Schutte_g1</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">hlm1</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span>, <span class="va">B</span> <span class="op">-</span> <span class="va">A</span><span class="op">)</span>, r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">Schutte_g1</span></code></pre></div>
<pre><code>##                           est    se
## unadjusted effect size -1.373 0.644
## adjusted effect size   -1.337 0.627
## degree of freedom      29.152</code></pre>
<p>It will be seen below that this initial model provides a poor fit to the data; thus, the effect size estimate based on it should not be trusted.</p>
</div>
<div id="varying-intercepts-fixed-treatment-effect-varying-trends" class="section level3">
<h3 class="hasAnchor">
<a href="#varying-intercepts-fixed-treatment-effect-varying-trends" class="anchor" aria-hidden="true"></a>Varying intercepts, fixed treatment effect, varying trends</h3>
<p>The next model (Model MB4) allows the baseline time trend to vary across cases. This can be done by modifying the previous model with the <code>update</code> function.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html" class="external-link">update</a></span><span class="op">(</span><span class="va">hlm1</span>, random <span class="op">=</span> <span class="op">~</span> <span class="va">week</span> <span class="op">|</span> <span class="va">case</span>, 
               control<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lmeControl.html" class="external-link">lmeControl</a></span><span class="op">(</span>msMaxIter <span class="op">=</span> <span class="fl">50</span>, apVar<span class="op">=</span><span class="cn">FALSE</span>, returnObject<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">hlm2</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Schutte 
##        AIC      BIC    logLik
##   875.9526 901.8978 -428.9763
## 
## Random effects:
##  Formula: ~week | case
##  Structure: General positive-definite, Log-Cholesky parametrization
##             StdDev   Corr  
## (Intercept) 9.783287 (Intr)
## week        1.412030 0.811 
## Residual    5.421656       
## 
## Correlation Structure: AR(1)
##  Formula: ~week | case 
##  Parameter estimate(s):
##       Phi 
## 0.3985953 
## Fixed effects:  fatigue ~ week + treatment + week_trt 
##                       Value Std.Error  DF   t-value p-value
## (Intercept)        50.29150  4.073625 121 12.345637  0.0000
## week                0.20271  0.616194 121  0.328968  0.7427
## treatmenttreatment -0.54218  1.751668 121 -0.309520  0.7575
## week_trt           -1.63198  0.655256 121 -2.490607  0.0141
##  Correlation: 
##                    (Intr) week   trtmnt
## week                0.883              
## treatmenttreatment -0.258 -0.200       
## week_trt           -0.567 -0.596 -0.178
## 
## Standardized Within-Group Residuals:
##         Min          Q1         Med          Q3         Max 
## -2.33194245 -0.46272153 -0.05348694  0.32878028  4.08749914 
## 
## Number of Observations: 136
## Number of Groups: 12</code></pre>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html" class="external-link">anova</a></span><span class="op">(</span><span class="va">hlm1</span>, <span class="va">hlm2</span><span class="op">)</span></code></pre></div>
<pre><code>##      Model df      AIC      BIC    logLik   Test  L.Ratio p-value
## hlm1     1  7 884.1744 904.3540 -435.0872                        
## hlm2     2  9 875.9526 901.8978 -428.9763 1 vs 2 12.22179  0.0022</code></pre>
<p>A likelihood ratio test rejects the initial model in favor of this more flexible model. An effect size estimate is calculated from the fitted model as follows<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>:</p>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Schutte_g2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">hlm2</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span>, <span class="va">B</span> <span class="op">-</span> <span class="va">A</span><span class="op">)</span>, r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">Schutte_g2</span></code></pre></div>
<pre><code>##                           est    se
## unadjusted effect size -1.070 0.495
## adjusted effect size   -1.013 0.469
## degree of freedom      14.302</code></pre>
<p>The design-comparable SMD is estimated to be -1.013, with a standard error of 0.469.</p>
</div>
<div id="varying-intercepts-varying-trends-varying-treatment-by-time-interactions" class="section level3">
<h3 class="hasAnchor">
<a href="#varying-intercepts-varying-trends-varying-treatment-by-time-interactions" class="anchor" aria-hidden="true"></a>Varying intercepts, varying trends, varying treatment-by-time interactions</h3>
<p>The final model (Model MB5) is yet more flexible, in that it allows the treatment-by-time interactions to vary across cases. Given that the data contain only twelve cases, fitting a model with three random effects would be questionable if the goal were to make inferences about the full structure of the model. However, simulation evidence from Pustejovsky, Hedges, and Shadish (2014) suggests that using such a flexible parameterization may nonetheless be reasonable for the more limited purpose of effect size estimation.</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">hlm3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/update.html" class="external-link">update</a></span><span class="op">(</span><span class="va">hlm2</span>, random <span class="op">=</span> <span class="op">~</span> <span class="va">week</span> <span class="op">+</span> <span class="va">week_trt</span> <span class="op">|</span> <span class="va">case</span>, 
               control<span class="op">=</span><span class="fu"><a href="https://rdrr.io/pkg/nlme/man/lmeControl.html" class="external-link">lmeControl</a></span><span class="op">(</span>msMaxIter <span class="op">=</span> <span class="fl">50</span>, apVar<span class="op">=</span><span class="cn">FALSE</span>, returnObject<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/summary.html" class="external-link">summary</a></span><span class="op">(</span><span class="va">hlm3</span><span class="op">)</span></code></pre></div>
<pre><code>## Linear mixed-effects model fit by REML
##   Data: Schutte 
##        AIC      BIC    logLik
##   873.0245 907.6181 -424.5123
## 
## Random effects:
##  Formula: ~week + week_trt | case
##  Structure: General positive-definite, Log-Cholesky parametrization
##             StdDev    Corr        
## (Intercept) 6.1884596 (Intr) week 
## week        0.3832993 0.162       
## week_trt    1.7351247 0.162  0.999
## Residual    4.7477472             
## 
## Correlation Structure: AR(1)
##  Formula: ~week | case 
##  Parameter estimate(s):
##       Phi 
## 0.2396137 
## Fixed effects:  fatigue ~ week + treatment + week_trt 
##                       Value Std.Error  DF   t-value p-value
## (Intercept)        50.52566 2.8214130 121 17.907928  0.0000
## week                0.21901 0.3640857 121  0.601537  0.5486
## treatmenttreatment  0.02697 1.5999246 121  0.016855  0.9866
## week_trt           -1.67113 0.7406249 121 -2.256378  0.0258
##  Correlation: 
##                    (Intr) week   trtmnt
## week                0.722              
## treatmenttreatment -0.357 -0.331       
## week_trt           -0.312 -0.283 -0.154
## 
## Standardized Within-Group Residuals:
##          Min           Q1          Med           Q3          Max 
## -2.559123387 -0.446173508 -0.004457334  0.366743786  4.597278939 
## 
## Number of Observations: 136
## Number of Groups: 12</code></pre>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/anova.html" class="external-link">anova</a></span><span class="op">(</span><span class="va">hlm2</span>, <span class="va">hlm3</span><span class="op">)</span></code></pre></div>
<pre><code>##      Model df      AIC      BIC    logLik   Test L.Ratio p-value
## hlm2     1  9 875.9526 901.8978 -428.9763                       
## hlm3     2 12 873.0245 907.6181 -424.5123 1 vs 2 8.92808  0.0303</code></pre>
<p>The REML estimation algorithm fails to converge because the estimate of the correlation between the random slopes and the random treatment-by-time interactions approaches 1. A likelihood ratio test rejects the previous model (which constrained the treatment-by-time interactions to be constant). However, this test cannot be trusted with such small sample of cases, and given variance component estimates that lie on an edge of the parameter space. An effect size estimate based on this fitted model is obtained as follows.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">Schutte_g3</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/lmeInfo.html">g_mlm</a></span><span class="op">(</span><span class="va">hlm3</span>, p_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span>,<span class="va">B</span> <span class="op">-</span> <span class="va">A</span><span class="op">)</span>, r_const <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">0</span>,<span class="fl">1</span><span class="op">)</span><span class="op">)</span>
<span class="va">Schutte_g3</span></code></pre></div>
<pre><code>##                           est    se
## unadjusted effect size -1.496 0.933
## adjusted effect size   -1.326 0.827
## degree of freedom       6.848</code></pre>
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># compare effect size estimates</span>
<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html" class="external-link">data.frame</a></span><span class="op">(</span>
  MB3 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">Schutte_g1</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"g_AB"</span>,<span class="st">"SE_g_AB"</span>,<span class="st">"nu"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>, 
  MB4 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">Schutte_g2</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"g_AB"</span>,<span class="st">"SE_g_AB"</span>,<span class="st">"nu"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>,
  MB5 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html" class="external-link">round</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="va">Schutte_g3</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/c.html" class="external-link">c</a></span><span class="op">(</span><span class="st">"g_AB"</span>,<span class="st">"SE_g_AB"</span>,<span class="st">"nu"</span><span class="op">)</span><span class="op">]</span><span class="op">)</span>, <span class="fl">3</span><span class="op">)</span>
<span class="op">)</span></code></pre></div>
<pre><code>##            MB3    MB4    MB5
## g_AB    -1.337 -1.013 -1.326
## SE_g_AB  0.627  0.469  0.827
## nu      29.152 14.302  6.848</code></pre>
<p>The effect size estimate has magnitude comparable to the estimate from Model MB3. However, the variance of the estimate is extremely large, due to the fact that the variance components that go into the denominator of the SMD estimate are estimated with low precision. This final model may represent an outer limit on the complexity of models that can feasibility be estimated, given that most single-case designs have fewer cases than the study examined in this example.</p>
</div>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor" aria-hidden="true"></a>References</h2>
<p>Anglesea, M. M., Hoch, H., &amp; Taylor, B. A. (2008). Reducing rapid eating in teenagers with autism: Use of a pager prompt. <em>Journal of Applied Behavior Analysis, 41</em>(1), 107–111. doi: <a href="https://doi.org/10.1901/jaba.2008.41-107" class="external-link">10.1901/jaba.2008.41-107</a></p>
<p>Hedges, L. V., Pustejovsky, J. E., &amp; Shadish, W. R. (2012). A standardized mean difference effect size for single case designs. <em>Research Synthesis Methods, 3</em>, 224-239. doi: <a href="https://doi.org/10.1002/jrsm.1052" class="external-link">10.1002/jrsm.1052</a></p>
<p>Hedges, L. V., Pustejovsky, J. E., &amp; Shadish, W. R. (2013). A standardized mean difference effect size for multiple baseline designs across individuals. <em>Research Synthesis Methods, 4</em>(4), 324-341. doi: <a href="https://doi.org/10.1002/jrsm.1086" class="external-link">10.1002/jrsm.1086</a></p>
<p>Lambert, M. C., Cartledge, G., Heward, W. L., &amp; Lo, Y. (2006). Effects of response cards on disruptive behavior and academic responding during math lessons by fourth-grade urban students. <em>Journal of Positive Behavior Interventions, 8</em>(2), 88-99.</p>
<p>Laski, K. E., Charlop, M. H., &amp; Schreibman, L. (1988). Training parents to use the natural language paradigm to increase their autistic children’s speech. <em>Journal of Applied Behavior Analysis, 21</em>(4), 391–400.</p>
<p>Pinheiro J., Bates D., DebRoy S., Sarkar D. and R Core Team (2015). <em>nlme: Linear and Nonlinear Mixed Effects Models</em>. R package version 3.1-119. <a href="https://CRAN.R-project.org/package=nlme" class="external-link uri">https://CRAN.R-project.org/package=nlme</a></p>
<p>Pustejovsky, J. E., Hedges, L. V., &amp; Shadish, W. R. (2014). Design-comparable effect sizes in multiple baseline designs: A general modeling framework. <em>Journal of Educational and Behavioral Statistics, 39</em>(4), 211-227. doi: <a href="https://doi.org/10.3102/1076998614547577" class="external-link">10.3102/1076998614547577</a></p>
<p>Pustejovsky, J. E., Hamilton, B. J., &amp; Chen, M. (2020). <em>scdhlm: Estimating hierarchical linear models for single-case designs</em>. R package version 0.3.2, <a href="https://jepusto.github.io/scdhlm/" class="uri">https://jepusto.github.io/scdhlm/</a>.</p>
<p>Saddler, B., Behforooz, B., &amp; Asaro, K. (2008). The effects of sentence-combining instruction on the writing of fourth-grade students with writing difficulties. <em>The Journal of Special Education, 42</em>(2), 79–90. doi: <a href="https://doi.org/10.1177/0022466907310371" class="external-link">10.1177/0022466907310371</a></p>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1">
<p>Note that the specification of the <code>r_const</code> argument here differs from the specification reported in Pustejovsky, Hedges, and Shadish (2014). The argument appears in a different order than reported in the article because of how the variance components are arranged in the <code><a href="../reference/lmeInfo.html">g_mlm()</a></code> function. To see the order of the variance components used by <code><a href="../reference/lmeInfo.html">g_mlm()</a></code>, use the <code><a href="../reference/lmeInfo.html">extract_varcomp()</a></code> function:</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/unlist.html" class="external-link">unlist</a></span><span class="op">(</span><span class="fu"><a href="../reference/lmeInfo.html">extract_varcomp</a></span><span class="op">(</span><span class="va">hlm2</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>##      Tau.case.case.var((Intercept)) Tau.case.case.cov(week,(Intercept)) 
##                          95.7126977                          11.2090726 
##             Tau.case.case.var(week)                          cor_params 
##                           1.9938298                           0.3985953 
##                            sigma_sq 
##                          29.3943508</code></pre>
<p>The order of parameter estimates appearing in the result is the same as assumed in <code><a href="../reference/lmeInfo.html">g_mlm()</a></code>. Thus, entries in <code>r_const</code> should correspond to the order of the parameter estimates appearing here.<a href="#fnref1" class="footnote-back">↩︎</a></p>
</li>
<li id="fn2"><p>Again, the specification of the <code>r_const</code> argument here differs from the specification reported in Pustejovsky, Hedges, and Shadish (2014). The entries in <code>r_const</code> should correspond to the order of the parameter estimates appearing in <code>unlist(extract_varcomp(hlm3))</code>.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p></p>
<p>Developed by <a href="https://www.jepusto.com/" class="external-link external-link">James Pustejovsky</a>, Man Chen, Bethany Hamilton.</p>
</div>

<div class="pkgdown">
  <p></p>
<p>Site built with <a href="https://pkgdown.r-lib.org/" class="external-link external-link">pkgdown</a> 1.9000.9000.9000.</p>
</div>

      </footer>
</div>

  
<script src="https://cdnjs.cloudflare.com/ajax/libs/docsearch.js/2.6.1/docsearch.min.js" integrity="sha256-GKvGqXDznoRYHCwKXGnuchvKSwmx9SRMrZOTh2g4Sb0=" crossorigin="anonymous"></script><script>
  docsearch({
    
    
    apiKey: '8b78ac1213f63fc369db7bf6b17c4bdd',
    indexName: 'scdhlm',
    inputSelector: 'input#search-input.form-control',
    transformData: function(hits) {
      return hits.map(function (hit) {
        hit.url = updateHitURL(hit);
        return hit;
      });
    }
  });
</script>
</body>
</html>
